Repository AR-TTUBEOG/Front-iOS, pull requests merged in 2024-01, with the labels that each got.

#2 Design : 글로벌 탐색바 생성
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/GlobalSearchControl/EasySeachModel.swift
  ttubeokAR/ttubeokAR/GlobalSearchControl/SearchControl.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/logo.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/logo.imageset/대지 2 5.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/option.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/option.imageset/option.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/search.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/search.imageset/search.png
Labels: 🖌️UI Develope

#3 Feat : MVVM으로 텍스트 필드 기능 구현 및 간편 검색 버튼 기능 구현
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/GlobalSearchControl/SearchButtonModel.swift
  ttubeokAR/ttubeokAR/GlobalSearchControl/SearchControl.swift
  ttubeokAR/ttubeokAR/GlobalSearchControl/SearchViewModel.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
Labels: ✨ Feature, 🖌️UI Develope

#4 Feat/ttuluttu dot
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchButtonModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/CircleDotButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuluttuDotShape.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuluttuDotViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuttuDotModel/ARCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuttuDotModel/AddLocationCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuttuDotModel/MyTicketCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuttuDotModel/SettingsCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuttuDotModel/TtuluttuDotCommand.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/ARBtn.imageset/ARBtn.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/ARBtn.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/AddLocation.imageset/AddLocation.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/AddLocation.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/MyTicket.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/MyTicket.imageset/MyTicket.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/OptionBtn.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/OptionBtn.imageset/OptionBtn.png
Labels: ✨ Feature, 🖌️UI Develope

#6 Design: 그라데이션 Background에서 fill로 전환
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuDotShape.swift
Labels: 🖌️UI Develope

#7 Feat: 폰트 extension 및 검색바 맵뷰 메인뷰에 따른 간편 검색 버튼 변경 기능
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchButtonModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuluttuDot/TtuDotButton.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/drink.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/drink.imageset/drink.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/restaurant.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/restaurant.imageset/Restaurant.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/trail.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/trail.imageset/trail.png
  ttubeokAR/ttubeokAR/SettingGroup/FontExtension.swift
Labels: ✨ Feature, 🖌️UI Develope

#8 Feat/ttuluttu dot
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/ARCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/AddLocationCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/MyTicketCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/SettingsCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/TtuDotModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotShape.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotViewModel.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/ARBtn.imageset/ARBtn.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/AddLocation.imageset/AddLocation.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/MyTicket.imageset/MyTicket.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/OptionBtn.imageset/OptionBtn.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/myPage.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TtuDotBtn/myPage.imageset/myPage.png
Labels: ✨ Feature, 🖌️UI Develope

#10 Feat: 메인 탭뷰 생성
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchButtonModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/MainTabBarControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/TabBarModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotShape.swift
  ttubeokAR/ttubeokAR/MapView/MapView.swift
  ttubeokAR/ttubeokAR/MapView/TestView.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TabButton/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TabButton/ExploreTabButton.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TabButton/ExploreTabButton.imageset/TabButton.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TabButton/mapTabButton.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/TabButton/mapTabButton.imageset/mapTabButton.pdf
  ttubeokAR/ttubeokAR/SettingGroup/ExtensionSize.swift
  ttubeokAR/ttubeokAR/SettingGroup/ScreenSize/ExtensionView.swift
  ttubeokAR/ttubeokAR/SettingGroup/ScreenSize/ScreenSizeModifier.swift
Labels: 🔨 Refactor, ✨ Feature, 🖌️UI Develope

#12 Feat: Color Assets 추가
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/Color.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/component/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/component/btnBackground.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/component/btnBackground2.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/component/search.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/component/stroke.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/font/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/font/darkGray.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/font/lightPurple.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/font/skyBlue.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/gradient/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/gradient/gradient03.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/background.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/primary01.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/primary02.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/primary03.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/primary04.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/sub1.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/main/sub2.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/point/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/point/green.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/point/lightGreen.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/point/lightGreen2.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/point/lightOrange.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/point/orange.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/point/red.colorset/Contents.json
Labels: ✨ Feature

#15 Feat/option popup view
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchButtonModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/CustomSlider.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingsViewModel.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/slider.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/slider.imageset/slider.pdf
Labels: ✨ Feature, 🖌️UI Develope

#16 Feat: 검색 설정창 푸시 팝업 뷰 기능 추가
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/CustomSlider.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/MainTabBarControl.swift
Labels: ✨ Feature, 🖌️UI Develope

#18 Feat: Custom NavigationBar 생성
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalNavigationBar/NavigationBar.swift
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
Labels: ✨ Feature

#20 Desgin: 팝업 푸시뷰가 화면 비율에 맞추어 위치, 크기 조절되도록 변경
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/Comparing main...feat:OptionPopupView · AR-TTUBEOG:Front-iOS.html
Labels: 🔨 Refactor, 🖌️UI Develope

#21 Fix : 홈버튼 버그 수정
  ttubeokAR/ttubeokAR/ExploreView/ExploreViewControl.swift
  ttubeokAR/ttubeokAR/ExploreView/RecommendedSpaceCard.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/MainTabBarControl.swift
Labels: 🐞 BugFix

#22 Design: 로그인 뷰 작성
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/checkbox_filled_purple.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/checkbox_filled_purple.imageset/checkbox_filled_purple.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/loginViewImage.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/loginViewImage.imageset/loginViewImage.jpg
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
  ttubeokAR/ttubeokAR/SocialLogin/LoginView.swift
Labels: 🖌️UI Develope

#23 feat: Coupon View 추가
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/CouponView/CouponModel/CouponModel.swift
  ttubeokAR/ttubeokAR/CouponView/CouponView.swift
  ttubeokAR/ttubeokAR/CouponView/CouponViewModel.swift
Labels: ✨ Feature

#27 Feat/login view
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/MainViewControl.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLoginViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleUserData.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView.swift
  ttubeokAR/ttubeokAR/MainContentView.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/appleLogin.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/appleLogin.imageset/appleLogin.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/kakao.imageset/kakao.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/kakaoLogin.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/kakaoLogin.imageset/kakaoLogin.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/nameWarning.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/nameWarning.imageset/nameWarning.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/nicknameView.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/nicknameView.imageset/nicknameView.jpg
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
Labels: ✨ Feature, 🖌️UI Develope

#24 Feat: Naver Map API 추가
  .gitignore
  ttubeokAR/Podfile
  ttubeokAR/Podfile.lock
  ttubeokAR/Secrets.xcconfig
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR.xcworkspace/contents.xcworkspacedata
  ttubeokAR/ttubeokAR.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ttubeokAR/ttubeokAR.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ttubeokAR/ttubeokAR/Info.plist
  ttubeokAR/ttubeokAR/MapView/Coordinator.swift
  ttubeokAR/ttubeokAR/MapView/Test/TestMapView.swift
Labels: ✨ Feature, ⚙ Setting

#36 Feat/kakao login
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ttubeokAR/ttubeokAR/Info.plist
  ttubeokAR/ttubeokAR/Login/NextContentView.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLoginManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginServerResponse.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginTarget.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
Labels: ✨ Feature, 🖌️UI Develope

#37 Feat: 설정뷰 화면 일부 구현 (등록된 장소 관리, 알림)
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalToggle/CustomToggle.swift
  ttubeokAR/ttubeokAR/SettingView/ManagePlaceSettingView.swift
  ttubeokAR/ttubeokAR/SettingView/NotiSettingView.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Manage/ManagePlaceViewModel.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Manage/Place.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Noti/NotiOption.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Noti/SettingViewModel.swift
Labels: ✨ Feature, 🖌️UI Develope

#38 Feat/kakao login
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Login/NextContentView.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLoginManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginTarget.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginView.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginViewCycle.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
Labels: 🔨 Refactor, ✨ Feature

#39 Feat: 닉네임 중복성 검사 API 연결
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameDuplicationAPI/NicknameRedundancyModel.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameDuplicationAPI/NicknameRedundancyService.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginView.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/loginViewImage.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/loginViewImage.imageset/loginViewImage.jpg
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/loginViewImage.imageset/loginViewImage.pdf
Labels: ✨ Feature, 🖌️UI Develope

#42 Feat/comment login
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/Comparing main...feat:appleLogin · AR-TTUBEOG:Front-iOS.html
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameDuplicationAPI/NicknameRedundancyService.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLoginManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleUserData.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLoginManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginServerResponse.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginTarget.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginView.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginViewCycle.swift
Labels: 📃 Docs

#43 Feat: 애플 로그인 토큰 파라미터 추가
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLoginManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleUserData.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginTarget.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
Labels: 🔨 Refactor, ✨ Feature

#44 Feat: 서버로부터 받은 토큰값 키체인에 등록
  ttubeokAR/Podfile.lock
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Login/SocialLogin/KeyChain/KeyChainManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginViewCycle.swift
Labels: ✨ Feature

#45 Docs: 추후 작업 해야할 토큰에 대해 주석 정리
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameDuplicationAPI/NicknameRedundancyService.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLoginManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/KeyChain/KeyChainManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginTarget.swift
Labels: 📃 Docs, 📬 API

#47 Feat/place setting
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/MainViewControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/SharedTabInfo.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/ARCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/AddLocationCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/MyTicketCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/SettingsCommand.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotModel/TtuDotModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotShape.swift
  ttubeokAR/ttubeokAR/Global/GlobalTtuDot/TtuDotViewModel.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLoginManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLoginManager.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/ButtonType/PlaceSelect.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/CloseCancelButton.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/Title/TitleView.swift
  ttubeokAR/ttubeokAR/PlaceSelect/PlaceSelectViewFlow/PlaceRegistrationView.swift
  ttubeokAR/ttubeokAR/PlaceSelect/PlaceSelectViewFlow/WhichSelectPlaceView.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/closeView.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/closeView.imageset/closeView.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
  ttubeokAR/ttubeokAR/ttubeokAR.entitlements
Labels: 🔨 Refactor, ✨ Feature, 🖌️UI Develope
