Repository AR-TTUBEOG/Front-iOS, pull requests merged in 2024-02, with the labels that each got.

#49 Feat: 설정화면 생성
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/SettingGroup/ColorAssets.xcassets/ColorAssets/point/pointPink.colorset/Contents.json
  ttubeokAR/ttubeokAR/SettingView/AccountSettingView.swift
  ttubeokAR/ttubeokAR/SettingView/EditorView.swift
  ttubeokAR/ttubeokAR/SettingView/ManagePlaceSettingView.swift
  ttubeokAR/ttubeokAR/SettingView/QuitSettingView.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Manage/ManagePlaceViewModel.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Manage/Place.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Manage/PlaceListViewModel.swift
  ttubeokAR/ttubeokAR/SettingView/SettingModel/Manage/PlaceViewModel.swift
Labels: ✨ Feature, 🖌️UI Develope

#51 Refactor: 로그인 API 주소 변경으로 인해 수정
  ttubeokAR/Podfile.lock
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginServerResponse.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginTarget.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
Labels: 🔨 Refactor, ✅ Test

#52 Refactor: 커스텀 네비게이션 바 수정
  ttubeokAR/ttubeokAR/CouponView/CouponView.swift
  ttubeokAR/ttubeokAR/Global/GlobalNavigationBar/NavigationBar.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/CloseCancelButton.swift
  ttubeokAR/ttubeokAR/SettingView/AccountSettingView.swift
  ttubeokAR/ttubeokAR/SettingView/EditorView.swift
  ttubeokAR/ttubeokAR/SettingView/NotiSettingView.swift
  ttubeokAR/ttubeokAR/SettingView/QuitSettingView.swift
Labels: 🔨 Refactor

#53 Feat/walk regist
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalButton/CloseCancelButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalButton/FinishButton.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/KeyChain/KeyChainManager.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/KeyChain/UserSession.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginViewCycle.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/ButtonType/MarketSelectButton.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/ButtonType/PlaceSelect.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/ButtonType/WalkSelectButton.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/FinishView/PlaceRegisterFinishView.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/ProgressNavigation/LinearProgressViewStyle.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/ProgressNavigation/PlaceRegisterNavigation.swift
  ttubeokAR/ttubeokAR/PlaceSelect/Duplicated/Text/CustomTitleView.swift
  ttubeokAR/ttubeokAR/PlaceSelect/PlaceSelectViewFlow/PlaceRegistrationView.swift
  ttubeokAR/ttubeokAR/PlaceSelect/PlaceSelectViewFlow/WalkRegister/WalkPlaceRegisterView.swift
  ttubeokAR/ttubeokAR/PlaceSelect/PlaceSelectViewFlow/WhichSelectPlaceView.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/nameCheck.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/nameCheck.imageset/nameCheck.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/RegisterBackground2.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/RegisterBackground2.imageset/RegisterBackground2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/placeFinish.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/placeFinish.imageset/placeFinish.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
Labels: 🔨 Refactor, ✨ Feature

#54 Feat/splash view
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Apple/AppleLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/Kakao/KakaoLogin.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/KeyChain/UserSession.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginAPI/LoginViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginView.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginViewCycle.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/loginViewImage.imageset/loginViewImage.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/logoImage.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Login/logoImage.imageset/logoImage.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
  ttubeokAR/ttubeokAR/Splash/SplashScreenView.swift
Labels: 🔨 Refactor, ✨ Feature

#55 Feat/market regist view
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/Global/GlobalButton/SelectMarketType.swift
  ttubeokAR/ttubeokAR/Global/GlobalTextField/CustomTextField.swift
  ttubeokAR/ttubeokAR/Global/GlobalTextField/CustomTitleView.swift
  ttubeokAR/ttubeokAR/Global/ImagePicker/ImageHandling.swift
  ttubeokAR/ttubeokAR/Global/ImagePicker/ImageSelectionButton.swift
  ttubeokAR/ttubeokAR/Global/ImagePicker/PlaceRegistImagePicker.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/ButtonType/MarketSelectButton.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/ButtonType/PlaceSelect.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/ButtonType/PlaceselectType.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/ButtonType/WalkSelectButton.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/FinishView/PlaceRegisterFinishView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/ProgressNavigation/LinearProgressViewStyle.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/ProgressNavigation/PlaceRegisterNavigation.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPlaceRegister.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketViewModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/PlaceRegistrationView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkPlaceRegisterView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayViewModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WhichSelectPlaceView.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/exampleMarket.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/exampleMarket.imageset/exampleMarket.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/exampleMarket2.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/exampleMarket2.imageset/exampleMarket2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/whiteDrink.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/whiteDrink.imageset/whiteDrink.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/whiteRest.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/whiteRest.imageset/whiteRest.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
Labels: 🔨 Refactor, ✨ Feature

#58 Feat/Map 지도뷰 어노테이션 리팩토링
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/MapView/Annotation/Anno.swift
  ttubeokAR/ttubeokAR/MapView/Annotation/AnnoButtonView.swift
  ttubeokAR/ttubeokAR/MapView/Annotation/AnnoViewModel.swift
  ttubeokAR/ttubeokAR/MapView/DetailPlaceView.swift
  ttubeokAR/ttubeokAR/MapView/Location/LocationManager.swift
  ttubeokAR/ttubeokAR/MapView/Network/Route.swift
  ttubeokAR/ttubeokAR/MapView/Network/RouteAPI.swift
  ttubeokAR/ttubeokAR/MapView/Network/RouteService.swift
  ttubeokAR/ttubeokAR/MapView/Network/RouteViewModel.swift
  ttubeokAR/ttubeokAR/MapView/Test/TestMap.swift
  ttubeokAR/ttubeokAR/MapView/Test/TestMapView.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/MapView/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/MapView/mapPlaceExample.imageset/1OOUA8RPQV_2 1.jpg
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/MapView/mapPlaceExample.imageset/1OOUA8RPQV_2 2.jpg
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/MapView/mapPlaceExample.imageset/1OOUA8RPQV_2.jpg
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/MapView/mapPlaceExample.imageset/Contents.json
Labels: 🔨 Refactor

#59 Feat/refactor api
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/ExploreView/ExploreAPI/APITarget/BookMarkAPI.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreAPI/APITarget/DetailExploreAPITarget.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreAPI/APITarget/ExploreAPITarget.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreAPI/APITarget/GuestBookAPI.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreAPI/APITarget/SearchAPITarget.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreDetail/DetailDataModel.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreDetail/DetailViewControl.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreDetail/DetailViewModel.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreDetail/GuestBookCard.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/ExploreViewControl.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/ExploreViewModel.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/RecommendedSpaceCard.swift
  ttubeokAR/ttubeokAR/ExploreView/PlaceTypeValue.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchOption/PlaceSettingsViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchType.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/MainViewControl.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/Union.imageset/Union.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/Union2.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/Union2.imageset/Union2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkCoupon.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkCoupon.imageset/coupon.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkGift.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkGift.imageset/giftIcon.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkHeart.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkHeart.imageset/Vector2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkStart.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkStart.imageset/starRating.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkTime.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/checkTime.imageset/time.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/nonCoupon.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/nonCoupon.imageset/coupon.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/nonGift.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/nonGift.imageset/giftIcon.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unCheckHeart.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unCheckHeart.imageset/Vector.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unDistance.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unDistance.imageset/distance2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unOnePlus.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unOnePlus.imageset/unOnePlus.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unTime.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unTime.imageset/time2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unstar.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/ExploreView/unstar.imageset/star2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/logo.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/logo.imageset/logo.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/searchLogo.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GlobalSearBarControl/searchLogo.imageset/searchLogo.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/backgroundLogo.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/backgroundLogo.imageset/backgroundLogo.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/coupon.imageset/coupon.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/game.imageset/game.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/start.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/Image/start.imageset/start.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
Labels: 🔨 Refactor, ✅ Test

#61 Feat/walkway api
  ttubeokAR/Podfile.lock
  ttubeokAR/Secrets.xcconfig
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/ExploreView/BookMark/BookMarkDataModel.swift
  ttubeokAR/ttubeokAR/ExploreView/BookMark/BookMarkImageAdd.swift
  ttubeokAR/ttubeokAR/ExploreView/BookMark/BookMarkImgProtocol.swift
  ttubeokAR/ttubeokAR/ExploreView/BookMark/BookMarkViewControl.swift
  ttubeokAR/ttubeokAR/ExploreView/BookMark/BookMarkViewModel.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreAPI/APITarget/ExploreAPITarget.swift
  ttubeokAR/ttubeokAR/Global/GlobalAddress/BaseLocationManager.swift
  ttubeokAR/ttubeokAR/Global/GlobalAddress/InputAddressProtocol.swift
  ttubeokAR/ttubeokAR/Global/GlobalAddress/InputAddressView.swift
  ttubeokAR/ttubeokAR/Global/GlobalButton/FinishButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalButton/SelectMarketType.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GameManager/gameButtonView.swift
  ttubeokAR/ttubeokAR/Global/GlobalImagePicker/ImageHandling.swift
  ttubeokAR/ttubeokAR/Global/GlobalTextField/CustomTitleView.swift
  ttubeokAR/ttubeokAR/Global/NaverGeoCoding/NaverReverseGeocodingAPI.swift
  ttubeokAR/ttubeokAR/Global/NaverGeoCoding/ReverseGeoCodingData.swift
  ttubeokAR/ttubeokAR/Global/NaverGeoCoding/ReverseGeocodingService.swift
  ttubeokAR/ttubeokAR/Info.plist
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameDuplicationAPI/NicknameRedundancyModel.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameDuplicationAPI/NicknameRedundancyService.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/KeyChain/KeyChainManager.swift
  ttubeokAR/ttubeokAR/MapView/Location/LocationManager.swift
  ttubeokAR/ttubeokAR/MapView/MapView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/FinishView/FinishViewProtocol.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/FinishView/PlaceRegisterFinishView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketViewModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/PlaceRegistrationView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkPlaceRegisterView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayViewModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalwayRegistAPI.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WhichSelectPlaceView.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GusetBookView/StarFilled.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GusetBookView/StarFilled.imageset/StarFilled.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Bundle.swift
  ttubeokAR/ttubeokAR/SettingGroup/KeyBoardExtension.swift
Labels: 📬 API, 🔨 Refactor, ✅ Test

#62 Feat/market regist api
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/ExploreViewControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalButton/RegistFinishButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/BasketBallGame/BasketBallGameRulesView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/BasketBallGame/BasketBallGameView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/BasketBallGame/BasketBallGameViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/BackgroundComponent.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/BenefitTextField/GameBenefitsText.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/BenefitTextField/GameBenefitsTextField.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/FinishButton/FinishButtonProtocol.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/FinishButton/GameSettingFinishButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/GameRulesTextView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/GameSettingSubTitle.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/SelectCouponRadio/GameCouponSelect.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/SelectCouponRadio/GameCouponView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GameManager/GameButtonView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GameManager/GameManagerView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GameManager/gameButtonView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GiftDrawingGame/GiftDrawingGameRulesView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GiftDrawingGame/GiftDrawingGameView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GiftDrawingGame/GiftDrawingGameViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGamePicker/WheelGamePicker.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGamePicker/WheelGamePickerMenu.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGamePicker/WheelGameRulesSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGameRuleView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGameShape/WheelGameShape.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGameShape/WheelGameShapeView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGameView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGameViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalTextField/CustomTextField.swift
  ttubeokAR/ttubeokAR/PlaceRegist/Duplicated/FinishView/PlaceRegisterFinishView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPlaceRegister.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketViewModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/PlaceRegistrationView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkPlaceRegisterView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WhichSelectPlaceView.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GameView/pickerBtn.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GameView/pickerBtn.imageset/pickerBtn.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GameView/wheelArrow.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/GameView/wheelArrow.imageset/wheelArrow.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/lightRegisterBackground2.imageset/Contents.json
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/PlaceSetting/lightRegisterBackground2.imageset/lightRegisterBackground2.pdf
  ttubeokAR/ttubeokAR/SettingGroup/Icon.swift
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#63 Feat/refactor code
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/ExploreViewControl.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/ExploreViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalAddress/BaseLocationManager.swift
  ttubeokAR/ttubeokAR/Global/GlobalAddress/InputAddressView.swift
  ttubeokAR/ttubeokAR/Global/GlobalButton/SelectMarketType.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/BasketBallGame/BasketBallGameRulesView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/BasketBallGame/BasketBallGameView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/BackgroundComponent.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/BenefitTextField/GameBenefitsText.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/BenefitTextField/GameBenefitsTextField.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/GameRulesTextView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/SelectCouponRadio/GameCouponSelect.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/DuplicatedGameManager/SelectCouponRadio/GameCouponView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GameManager/GameManagerView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GiftDrawingGame/GiftDrawingGameRulesView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/GiftDrawingGame/GiftDrawingGameView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGamePicker/WheelGamePicker.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGamePicker/WheelGameRulesSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGameRuleView.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGameView.swift
  ttubeokAR/ttubeokAR/Global/GlobalImagePicker/ImageSelectionButton.swift
  ttubeokAR/ttubeokAR/Global/GlobalSearchControl/SearchBar/SearchControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalTabBar/MainViewControl.swift
  ttubeokAR/ttubeokAR/Global/GlobalTextField/CustomTextField.swift
  ttubeokAR/ttubeokAR/Global/GlobalTextField/CustomTitleView.swift
  ttubeokAR/ttubeokAR/Info.plist
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingLogin.swift
  ttubeokAR/ttubeokAR/Login/NicknameLogin/NicknameSettingViewModel.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginViewCycle.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPlaceRegister.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketViewModel.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/PlaceRegistrationView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkPlaceRegisterView.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/WalkRegister/WalkwayViewModel.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/100.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/1024.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/114.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/120.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/144.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/152.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/167.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/180.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/20.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/29.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/40.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/50.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/57.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/58.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/60.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/72.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/76.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/80.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/87.png
  ttubeokAR/ttubeokAR/SettingGroup/Assets.xcassets/AppIcon.appiconset/Contents.json
  ttubeokAR/ttubeokAR/Splash/SplashScreenView.swift
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#64 Refactor: 지도 화면 수정
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/MapView/Annotation/Anno.swift
  ttubeokAR/ttubeokAR/MapView/Annotation/AnnoButtonView.swift
  ttubeokAR/ttubeokAR/MapView/Annotation/AnnoViewModel.swift
  ttubeokAR/ttubeokAR/MapView/DetailPlaceView.swift
  ttubeokAR/ttubeokAR/MapView/Road/Road.swift
  ttubeokAR/ttubeokAR/MapView/Road/RoadListViewModel.swift
  ttubeokAR/ttubeokAR/MapView/Road/RoadViewModel.swift
  ttubeokAR/ttubeokAR/MapView/Test/TestMap.swift
Labels: 🔨 Refactor

#66 Feat/refactor code
  ttubeokAR/ttubeokAR.xcodeproj/project.pbxproj
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/ExploreViewControl.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/ExploreViewModel.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/SpaceCard/RecommendedSpaceCard.swift
  ttubeokAR/ttubeokAR/ExploreView/ExploreMain/SpaceCard/RecommendedSpaceCardViewModel.swift
  ttubeokAR/ttubeokAR/Global/GlobalAddress/BaseLocationManager.swift
  ttubeokAR/ttubeokAR/Global/GlobalGameManager/WheelGame/WheelGamePicker/WheelGameRulesSettingView.swift
  ttubeokAR/ttubeokAR/Global/GlobalTextField/CustomTextField.swift
  ttubeokAR/ttubeokAR/Login/SocialLogin/LoginView/LoginViewCycle.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPageContent.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketPlaceRegister.swift
  ttubeokAR/ttubeokAR/PlaceRegist/PlaceRegistViewFlow/MarketRegister/MarketViewModel.swift
  ttubeokAR/ttubeokAR/SettingGroup/AppDelegate.swift
  ttubeokAR/ttubeokAR/Splash/PermissionViewModel.swift
  ttubeokAR/ttubeokAR/Splash/SplashScreenView.swift
Labels: 🔨 Refactor, ✨ Feature
